CREATE TEMPORARY TABLE test (
	value INTEGER NOT NULL PRIMARY KEY
);

INSERT INTO test SELECT 1;
INSERT INTO test SELECT 2;
INSERT INTO test SELECT 3;
INSERT INTO test SELECT 4;
INSERT INTO test SELECT 5;